export enum CategoryType {
  FOOD = 'FOOD',
  TRANSPORT = 'TRANSPORT',
  ENTERTAINMENT = 'ENTERTAINMENT',
  UTILITIES = 'UTILITIES',
  SHOPPING = 'SHOPPING',
  EDUCATION = 'EDUCATION',
  HEALTH = 'HEALTH',
  SALARY = 'SALARY',
  INVESTMENT = 'INVESTMENT',
  OTHER = 'OTHER',
}
