import { Transaction } from '../domain/entities/transaction.entity';
import { TransactionType } from '../domain/enums/transaction-type.enum';

export const TRANSACTIONS_MOCK: Transaction[] = [
  {
    id: '1',
    userId: '1',
    categoryId: '1',
    type: TransactionType.EXPENSE,
    amount: 45.99,
    currency: 'USD',
    description: 'Lunch at restaurant',
    date: new Date('2024-10-15'),
    createdAt: new Date('2024-10-15'),
    updatedAt: new Date('2024-10-15'),
  },
  {
    id: '2',
    userId: '1',
    categoryId: '2',
    type: TransactionType.EXPENSE,
    amount: 120.0,
    currency: 'USD',
    description: 'Gas station',
    date: new Date('2024-10-16'),
    createdAt: new Date('2024-10-16'),
    updatedAt: new Date('2024-10-16'),
  },
  {
    id: '3',
    userId: '1',
    categoryId: '5',
    type: TransactionType.INCOME,
    amount: 5000.0,
    currency: 'USD',
    description: 'Monthly salary',
    date: new Date('2024-10-01'),
    createdAt: new Date('2024-10-01'),
    updatedAt: new Date('2024-10-01'),
  },
  {
    id: '4',
    userId: '2',
    categoryId: '3',
    type: TransactionType.EXPENSE,
    amount: 85.0,
    currency: 'USD',
    description: 'Movie tickets and popcorn',
    date: new Date('2024-10-18'),
    createdAt: new Date('2024-10-18'),
    updatedAt: new Date('2024-10-18'),
  },
  {
    id: '5',
    userId: '1',
    categoryId: '4',
    type: TransactionType.EXPENSE,
    amount: 200.0,
    currency: 'USD',
    description: 'Electricity bill',
    date: new Date('2024-10-10'),
    createdAt: new Date('2024-10-10'),
    updatedAt: new Date('2024-10-10'),
  },
];
