import { Category } from '../domain/entities/category.entity';
import { CategoryType } from '../domain/enums/category-type.enum';

export const categoriesMock: Category[] = [
  {
    id: '1',
    userId: 'default',
    name: 'Food & Dining',
    type: CategoryType.FOOD,
    color: '#FF6B6B',
    icon: '🍔',
    isDefault: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    userId: 'default',
    name: 'Transportation',
    type: CategoryType.TRANSPORT,
    color: '#4ECDC4',
    icon: '🚗',
    isDefault: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    userId: 'default',
    name: 'Entertainment',
    type: CategoryType.ENTERTAINMENT,
    color: '#95E1D3',
    icon: '🎬',
    isDefault: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    userId: 'default',
    name: 'Utilities',
    type: CategoryType.UTILITIES,
    color: '#F38181',
    icon: '💡',
    isDefault: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    userId: 'default',
    name: 'Salary',
    type: CategoryType.SALARY,
    color: '#6C5CE7',
    icon: '💰',
    isDefault: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    userId: '1',
    name: 'Gym Membership',
    type: CategoryType.HEALTH,
    color: '#A8E6CF',
    icon: '💪',
    isDefault: false,
    createdAt: new Date('2024-02-01'),
  },
];
