import { Budget } from '../domain/entities/budget.entity';
import { BudgetPeriod } from '../domain/enums/budget-period.enum';
import { BudgetStatus } from '../domain/enums/budget-status.enum';

export const budgetsMock: Budget[] = [
  {
    id: '1',
    userId: '1',
    categoryId: '1',
    limitAmount: 500.0,
    limitCurrency: 'USD',
    spentAmount: 345.99,
    period: BudgetPeriod.MONTHLY,
    status: BudgetStatus.ACTIVE,
    startDate: new Date('2024-10-01'),
    endDate: new Date('2024-10-31'),
    alertThreshold: 80,
    createdAt: new Date('2024-09-25'),
  },
  {
    id: '2',
    userId: '1',
    categoryId: '2',
    limitAmount: 300.0,
    limitCurrency: 'USD',
    spentAmount: 120.0,
    period: BudgetPeriod.MONTHLY,
    status: BudgetStatus.ACTIVE,
    startDate: new Date('2024-10-01'),
    endDate: new Date('2024-10-31'),
    alertThreshold: 80,
    createdAt: new Date('2024-09-25'),
  },
  {
    id: '3',
    userId: '1',
    categoryId: '4',
    limitAmount: 250.0,
    limitCurrency: 'USD',
    spentAmount: 200.0,
    period: BudgetPeriod.MONTHLY,
    status: BudgetStatus.WARNING,
    startDate: new Date('2024-10-01'),
    endDate: new Date('2024-10-31'),
    alertThreshold: 80,
    createdAt: new Date('2024-09-25'),
  },
  {
    id: '4',
    userId: '2',
    categoryId: '3',
    limitAmount: 200.0,
    limitCurrency: 'USD',
    spentAmount: 85.0,
    period: BudgetPeriod.MONTHLY,
    status: BudgetStatus.ACTIVE,
    startDate: new Date('2024-10-01'),
    endDate: new Date('2024-10-31'),
    alertThreshold: 80,
    createdAt: new Date('2024-09-25'),
  },
];
